server.error:
  include-exception: true
  include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/student_grade_managements
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
logging:
  level: debug

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
