create table student_classroom (
    id bigint generated by default as identity,
    class_id bigint,
    student_id bigint,
    primary key (id)
)

create table student (
    id bigint generated by default as identity,
    grade integer,
    name varchar(20),
    school_name varchar(20),
    primary key (id)
)

create table class_room (
    id bigint generated by default as identity,
    end_date timestamp,
    name varchar(100),
    start_date timestamp,
    teacher_name varchar(20),
    primary key (id)
)

create table subject (
     id bigint generated by default as identity,
     name varchar(100),
     class_id bigint,
     primary key (id)
)

create table grade (
    id bigint generated by default as identity,
    score integer not null,
    student_id bigint,
    subject_id bigint,
    primary key (id)
)

alter table student_classroom
    add constraint FKck2byba3b0ho1p1ejd1f1urud
        foreign key (class_id)
            references class_room

alter table subject
    add constraint FK2b7c0ctjgk8ay5ordn8tmp1eh
        foreign key (class_id)
            references class_room

alter table student_classroom
    add constraint FK4gqo6scoya0b2xkxaot9g843c
        foreign key (student_id)
            references student

alter table grade
    add constraint FK5secqnjjwgh9wxk4h1xwgj1n0
        foreign key (student_id)
            references student

alter table grade
    add constraint FKhhw6hbmiyabjlm1jghr00m5d8
        foreign key (subject_id)
            references subject